export const HOMEPAGE = '/'
export const PRODUCT_LIST = '/products'
export const CART = '/cart'
export const SIGN_UP = '/signup'
export const LOGIN = '/login'
export const ACCOUNT = '/account'
export const LOGOUT = '/logout'
